spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kochet-diplom
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: palette



jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800


#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

